version: "3"

services:
  postgres:
    container_name: ecommerce_db
    image: postgres
    environment: 
      POSTGRES_USER: "ecommerce_user"
      POSTGRES_PASSWORD: "ecommerce_password"
      PGDATA: /data/ecommerce_postgres
    volumes:
      - postgres:/data/ecommerce_postgres
    ports:
      - "5436:5432"
    networks:
      - ecommerce_net
    restart: unless-stopped

networks:
  ecommerce_net:
    driver: bridge

volumes:
  postgres:

  # 127.0.0.1